### ISSUE TITLE
many problems exist with having more than 1000 files at the root folder

### ISSUE THREAD

**Issue by rvion** [commercialhaskell/all-cabal-files#1]
Can all cabal package folders be moved in a sub folder ?
the problem with them beeing at the root of the github repo are:
- one has to scoll a lot to read the readme
- a warning sign is displayed making the repository feel sloppy
- page is slow to load
- some files like gitignore or readme could possibly not be displayed in the file index
- weird ordering leave false impression that all proejcts are present (there is ~1000 packages starting with cap letters, so one can see package starting with A end lasts ending with Z, and jump to weird conclusion)
- also, to be super picky, the way github sometimes concatenate subfolders names (when only one sub-items is present) make the names not appear a coherent way when only one version released

**Comment by snoyberg** [comment]
I kept it this way specifically to mirror the 00-index file, so that it would be trivial to clone this repo in ~/.cabal/package/hackage.haskell.org. I agree with all your points, but I think making it easy to use this as a replacement for `cabal update` is more important than viewing convenience.

**Comment by rvion** [comment]
thanks for the answer, I completely agree with you so

**Comment by snoyberg** [comment]
I think I'll add a link to this issue from the README, since you raised some very solid points that others will likely have.

**Comment by rvion** [comment]
I think your explanation would even worth being in the readme direclty in a ## About this git repository structure
Edit: you've already done it, thanks :)

**Comment by snoyberg** [comment]
PR welcome :)
