### ISSUE TITLE
Please configure git to track these files using a consistent line ending style

### ISSUE THREAD

**Issue by peti** [commercialhaskell/all-cabal-files#11]
Hackage has adopted the unpleasant habit of adding CRLF endings to Cabal files that were edited, so line endings tend to change all over the file when a new revision is added. It would be nice to use git's line-ending conversion features to avoid this issue.

**Comment by snoyberg** [comment]
Wow, that's terrible. Have you opened up an issue upstream with Hackage about that? That should _really_ be fixed there too.

I'm somewhat hesitant to do this, because it violates the rules this repo has generally followed (make no changes to upstream). But I'm sympathetic to how bad this is.

Do you know offhand the right incantation to get `git` to do this?

**Comment by snoyberg** [comment]
Looks like this'll do it:

```
git config --global core.autocrlf input
```

**Comment by peti** [comment]
> git config --global core.autocrlf input

Yes, I believe that is the right choice. I haven't complained to Hackage yet, but I will ASAP.

**Comment by snoyberg** [comment]
I put out a Twitter poll to see if people have thoughts on this, I'm still a bit concerned about doing this due to the potential to modify the .cabal files in ways that authors weren't expecting (however seemingly inconsequential that may be).

https://twitter.com/snoyberg/status/771007650184192000

**Comment by snoyberg** [comment]
Alright, it's merged. I'll wait for you to review new changes before closing.

**Comment by snoyberg** [comment]
Closing, I also pinged the relevant issue on Hackage (haskell/hackage-server#316).

**Comment by peti** [comment]
These changes fix newly imported Cabal files, but edited Cabal files that were imported before still use MS-DOS line endings, i.e. `esqueleto/2.4.3/esqueleto.cabal`.
