### ISSUE TITLE
Having separate branch for each set (hacakge/ stackage / etc. )

### ISSUE THREAD

**Issue by rvion** [commercialhaskell/all-cabal-files#2]
As @snoyberg said in #1, this repository is aimed at tools, and git doesn't allow easilly to clone subdirectories, so cabal folders need to be at root.

But git allows to **clone branches**, so we could possibly have one branch per set of package.

we could have:
- https://github.com/commercialhaskell/all-cabal-files/tree/hackage  (all cabal files for hackage) (this is currently master)
- https://github.com/commercialhaskell/all-cabal-files/tree/stacakge (all cabal files for stackage)

and 
- https://github.com/commercialhaskell/all-cabal-files  (master branch would primarily be a for humans: readme + list to specific branches + explanations)

This would reduce noise in several situations.
This is just an idea I'm noting here in case it worth anything

**Comment by rvion** [comment]
Other benefits:
- Later extensibility in case of new package sets (hackage/stacakge/**abcdef**/...)
- In case it helps with **speed** when pulling , we could have low-number-of-commits branches automaticaly created every weeks (weekly-hackage / weekly-stackage / weekly-abcdef).

**Comment by snoyberg** [comment]
I set up the update script to push to hackage as well, and decided to use that in the [stackage-update](http://hackage.haskell.org/package/stackage-update) code. But changes to the master branch will cause problems with the current way updating works, so I'd rather not jump into it.

**Comment by snoyberg** [comment]
I just changed the default branch on Github, so that it shows "display". If you have other ideas for improvements, please send them as PRs against that branch. Thanks!

https://github.com/commercialhaskell/all-cabal-files
