### ISSUE TITLE
What is the difference between "master" and "hackage"?

### ISSUE THREAD

**Issue by peti** [commercialhaskell/all-cabal-files#3]
Both branches contain identical content, but I reckon they're conceptually different somehow? Is it a mistake to use `master`?

**Comment by snoyberg** [comment]
We may end up using master for something else in the future. I'd recommend
using hackage for now. See the discussion on #1 and #2 for more details. I
haven't made up my mind about these topics at all, and welcome input on the
matter.

**Comment by peti** [comment]
OK. Thank you for the quick response!
