### ISSUE TITLE
Please use date stamps that conform to ISO 8601

### ISSUE THREAD

**Issue by peti** [commercialhaskell/all-cabal-files#6]
It would be nice if commit messages used the date stamp that is generated by

```
$ date --utc --iso=sec
2015-04-17T16:04:48+0000
```

to conform to ISO 8601.

**Comment by snoyberg** [comment]
I only included the dates for informational purposes (and in fact they're duplicated by the date in the commit). However, I don't see harm in changing this, so I've gone ahead with it.
