### ISSUE TITLE
preferred-versions file seems to be missing

### ISSUE THREAD

**Issue by peti** [commercialhaskell/all-cabal-files#7]
This repository doesn't seem to track the `preferred-versions` file. Is there a particular reason why that file is absent?

**Comment by snoyberg** [comment]
What makes you say that?

https://github.com/commercialhaskell/all-cabal-files/blob/master/preferred-versions

**Comment by peti** [comment]
Sorry, my mistake. Apparently I was confused.

**Comment by snoyberg** [comment]
No problem. This did trigger me noticing that all-cabal-hashes doesn't have this file, which is hopefully going to be resolved in the next Travis build.
