### ISSUE TITLE
preferred versions update for cabal-helper doesn't show up in repository

### ISSUE THREAD

**Issue by peti** [commercialhaskell/all-cabal-files#8]
The preferred-versions file in this repository,
https://github.com/commercialhaskell/all-cabal-files/blob/hackage/preferred-versions#L54, doesn't reflect a change that was made approximately 10 days ago  (according to https://github.com/DanielG/cabal-helper/issues/10#issuecomment-134993492). Version 0.5.2.0 should be marked deprecated, but apparently it's not. Am I missing something?

**Comment by snoyberg** [comment]
Hackage doesn't list it as deprecated, at least afaict:

http://hackage.haskell.org/package/cabal-helper

**Comment by peti** [comment]
Huh? To me, http://hackage.haskell.org/package/cabal-helper/preferred says loud and clear that 0.5.2.0 is deprecated, and on the home page, http://hackage.haskell.org/package/cabal-helper, the version appears in a slightly gray'ish color, too. Are you behind a caching proxy, maybe?

**Comment by snoyberg** [comment]
No, I was just reading from my phone and somehow didn't see that
information.

**Comment by peti** [comment]
OK. Any idea why the `preferred-versions` file isn't updated?

**Comment by snoyberg** [comment]
Yup, just checked: the file is no longer provided by the upstream tarball on Hackage. I'm guessing this is a bug introduced by the recent TUF work (pinging @dcoutts @edsko). I'd recommend filing an issue on Hackage, there's nothing we can do here.

**Comment by edsko** [comment]
Will check now.

**Comment by edsko** [comment]
Sorry, which tarball are we talking about?

```
# curl -OL http://hackage.haskell.org/00-index.tar.gz
# tar tvfz 00-index.tar.gz | grep preferred | grep cabal-helper
-rw-r--r--  0 0      0          57 Aug 20 05:38 cabal-helper/preferred-versions
# tar xvfz 00-index.tar.gz cabal-helper/preferred-versions
x cabal-helper/preferred-versions
# cat cabal-helper/preferred-versions 
cabal-helper <0.1.0.0 || >0.1.0.0 && <0.5.2.0 || >0.5.2.0
```

**Comment by snoyberg** [comment]
There has always been a preferred-versions file in the root of the tarball, at least until now.

**Comment by snoyberg** [comment]
To see what this file used to look like:

https://github.com/commercialhaskell/all-cabal-files/blob/hackage/preferred-versions

**Comment by edsko** [comment]
While that is true, this was never a proper part of the index "specification" proper; of course, I use "specification" very loosely here, as an actual specification of the index tarball never existed, which is Bad Thing (it's actually on the TODO list for the final TUF release); but for example `cabal-install` has accumulated all `preferred-versions` from the index tarball since way back (https://github.com/haskell/cabal/blob/8b702f6d95f92b58f94690c48ef3e5599072cae2/cabal-install/Distribution/Client/IndexUtils.hs#L83-L118). Nonetheless I am sorry that this "change" has broken other existing code; I have opened a Hackage ticket (https://github.com/haskell/hackage-server/issues/414) to discuss this issue.

**Comment by peti** [comment]
@snoyberg, would it be possible to get the individual `preferred-version` files included in the repository quickly? With those available, I wouldn't need the top-level file any more. Also, it would be great to have those files available in https://github.com/commercialhaskell/all-cabal-hashes/, too, as that's the repository we actually use to update Nixpkgs.

**Comment by snoyberg** [comment]
It's already present in all-cabal-files:

https://github.com/commercialhaskell/all-cabal-files/blob/hackage/cabal-helper/preferred-versions

I'll look into all-cabal-hashes too, it should be too difficult.

**Comment by peti** [comment]
`all-cabal-hashes` has them as well! Very nice; this allows me to work around this issue quite easily.

**Comment by snoyberg** [comment]
It does? I'm not seeing it, though I may just be acting dense again ;)

**Comment by peti** [comment]
No, sorry. I was in the wrong directory when I looked for them. The files are, in fact, not there in `all-cabal-hashes`. Sorry for the confusion.

**Comment by snoyberg** [comment]
I'll also delete the old preferred-versions files to avoid confusion

**Comment by snoyberg** [comment]
Alright, should be in place. I also updated the all-cabal-hashes-tool to a stack-based Travis build with caching, so future changes should deploy much faster. @peti can you check it out?

**Comment by peti** [comment]
Worked like a charm -- the files are there. Thank you for the quick fix.

**Comment by snoyberg** [comment]
No problem.
