### ISSUE TITLE
How to recognize deprecated packages?

### ISSUE THREAD

**Issue by peti** [commercialhaskell/all-cabal-files#9]
Is there a way to recognize from the data in this repository that a package has been deprecated?

And if the answer is _no_, would it be possible to add that information?

**Comment by snoyberg** [comment]
No, it's a separate Hackage API call:

http://hackage.haskell.org/packages/deprecated.json

Right now, this repo is pretty much a strict copy of the 00-index.tar file. I'm not necessarily opposed to changing that, but based on your previous comments: would this be better for you in all-cabal-hashes anyway?

**Comment by peti** [comment]
Yes, you are right. I use `all-cabal-hashes`, so if the deprecation list were included in there then that would be just fine for me.

**Comment by snoyberg** [comment]
What do you think about just including that raw JSON output as deprecated.json at the root of the repo?

**Comment by peti** [comment]
Sure, that would work for me.

**Comment by snoyberg** [comment]
Alright, try it out now. For future issues, let's track it on the all-cabal-hashes-tool repo instead.

**Comment by peti** [comment]
The file is there. Thank you very much for the quick fix!
